In [2]:
import numpy as np 

arr_1 = np.array([[1,2,3],[4,5,6]])
arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
#Sumar todos los numeros, segundo parametro axis=0,1,
#con 1 hace en horizontal con 0 hace en vertical

#con .prod hacemos lo mismo pero el producto y tb tiene
#el parametro axis
np.sum(arr_1)

array([ 6, 15])

In [4]:
np.sum(arr_1, axis=0)

array([5, 7, 9])

In [5]:
np.sum(arr_1, axis=1)

array([ 6, 15])

In [6]:
# .min tb tiene axis, tb existe .max()
arr_1.min(axis=0)

array([1, 2, 3])

In [7]:
#.argmin y argmax nos dice el indice de donde se encuentra
#tb tiene axis, y si no se pone estamos hablando del array entero
arr_1.argmin(axis=1)

array([0, 0], dtype=int64)

In [8]:
# .mean lo q hace es hacer la media de la matriz y tb puede usar axis
#como siempre axis=0 para horizontal axis=1 para vertical
arr_1.mean(axis=0)

array([2.5, 3.5, 4.5])

In [9]:
#.std() nos estandariza los datos como se hace en machine learning, tb se puede
#usar axis=0 y axis=1
arr_1.std()

1.707825127659933

In [10]:
#la varianza se saca con .var() y tb usa axis
arr_1.var()

2.9166666666666665

In [11]:
#funcion .clip(x,y) cambia a x los numeros por debajo de x y a y los numeros por encima de y,
#el resto se queda igual
arr_1.clip(2,4)

array([[2, 2, 3],
       [4, 4, 4]])

In [13]:
arr_2 = np.array([4.12,5.5,6.666])
#round tiene el paramtero decimals=x para redondear a los decimales que queramos, por defecto es 0
arr_2.round(decimals=2)

array([4.12, 5.5 , 6.67])

In [16]:
#FUNCIONES DE SORT EN NUMPY
arr_1 = np.array([[5.5,1.1,8.7],[4.5,9.8,0.9]])
arr_1

array([[5.5, 1.1, 8.7],
       [4.5, 9.8, 0.9]])

In [17]:
#np.sort(x) nos ordena de menor a menor las filas
#pero no cambia arr_1 IMPORTANTE
np.sort(arr_1)

array([[1.1, 5.5, 8.7],
       [0.9, 4.5, 9.8]])

In [18]:
arr_1

array([[5.5, 1.1, 8.7],
       [4.5, 9.8, 0.9]])

In [20]:
#np.argsort(x) nos dice en q posicion iria el elemento i si se ordenara
print(np.argsort(arr_1), arr_1)

[[1 0 2]
 [2 0 1]] [[5.5 1.1 8.7]
 [4.5 9.8 0.9]]


In [21]:
#np.searchsorted(x,y) nos dice en q orden pondriamos los elementos y de x
arr_2 = np.arange(0,10) #array de 10 posiciones de 0 a 9
arr_3 = np.array([3.4,6.7,7.8])
np.searchsorted(arr_2,arr_3)

array([4, 7, 8], dtype=int64)

In [22]:
#CONTROL DE DATOS DENTRO DE NUMPY
arr_1 = np.arange(10)
arr_1.shape

(10,)

In [23]:
#podemos desestructurar el array para convertirlo en una matriz con shape,
#pero tiene que cuadrar, por ejemplo no podemos hacer 2 filas de 6 elementos si tenemos 10 elementos
arr_1.shape = 2,5
arr_1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
#para devolver el array a su posicion podemos usar reshape, donde el primer elemento es el numero de filas y 
#el segundo el numero de columnas
arr_1.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
#Podemos crear ejes nuevos en las matrices escribiendo np.newaxis en el constructor tal que asi
arr_2 = np.arange(10)
arr_3 = arr_2[:, np.newaxis]
arr_3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [30]:
#podemos hacer todas las dimensiones que queramos
arr_4 = arr_2[:,np.newaxis, np.newaxis]
arr_4.shape

(10, 1, 1)

In [31]:
#con .squeeze nos convertimos cualquier matriz en un array de 1 dimension
arr_4.squeeze()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#con transpose transponemos la matriz
arr_4.shape = 2,5
#Es lo mismo escribir .T que .transpose()
arr_5 = arr_4.transpose()
arr_5

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [37]:
#np.concatenate nos une las matrices, tambien usa axis=0 para vertical y axis=1 para horizontal
arr_6 = np.array([[1,2,3],[4,5,6]])
arr_7 = np.array([[41,51,61],[71,81,91]])
arr_8 = np.concatenate((arr_6, arr_7), axis=0)
arr_8

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [41, 51, 61],
       [71, 81, 91]])

In [39]:
# con .vstack y .hstack es lo mismo, v para vertical h para horizontal
np.vstack((arr_6, arr_7))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [41, 51, 61],
       [71, 81, 91]])

In [40]:
np.hstack((arr_6,arr_7))

array([[ 1,  2,  3, 41, 51, 61],
       [ 4,  5,  6, 71, 81, 91]])

In [42]:
#x.flatten() nos convierte todo en una linea, igual que .ravel(), pero no cambia el estado de x IMPORTANTE
arr_8.flatten()


array([ 1,  2,  3,  4,  5,  6, 41, 51, 61, 71, 81, 91])

In [43]:
#FUNCIONES PARA CREAR ARRAYS EN NUMPY
# de 5 a 40 de 5 en 5, se puede pasar un cuarto parametro para dar un tipo de dato
arr_1 = np.arange(5,40,5, dtype=np.float32)
arr_1

array([ 5., 10., 15., 20., 25., 30., 35.], dtype=float32)

In [44]:
#np.linspace lo que hace es encontrar la cantidad de numeros que queremos(equidistantes entre 2 numeros)
#En el ejemplo que hay en este bloque nos muestra 30 numeros que vayan de 0 a 10
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [50]:
#crear un grid con 2 matrices
arr_1 = np.linspace(-10,10,5)
arr_2 = np.linspace(10,20,5)

x, y = np.meshgrid(arr_1,arr_2)

In [51]:
#Grid donde todas las filas son arr_1
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [52]:
#grid donde todas las columnas son arr_2
y

array([[10. , 10. , 10. , 10. , 10. ],
       [12.5, 12.5, 12.5, 12.5, 12.5],
       [15. , 15. , 15. , 15. , 15. ],
       [17.5, 17.5, 17.5, 17.5, 17.5],
       [20. , 20. , 20. , 20. , 20. ]])

In [57]:
#Misma funcion que arange para hacer una fila
#Con esta funcion el array se genera in situ por lo que no puede ser asignado a nada
np.r_[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
#Misma que r_ para hacer una columna
np.c_[0:10:1]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [62]:
#.zeros array de 0, .ones array de 1
np.zeros(3, dtype=np.int)

array([0, 0, 0])

In [64]:
np.zeros((3,5), dtype = np.int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [68]:
#np.zeros_like(x) hace una matriz de 0 del mismo shape que x
#Tambien existe ones_like
arr_3 = np.arange(0,10)
np.zeros_like(arr_3)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [69]:
#np.identity nos saca la matriz de identidad
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [73]:
#OPERACIONES LOGICAS CON NUMPY
arr_1 = np.array([[1,1,1,1],[1,1,1,1]])
arr_2 = np.array([[1,1,1,8],[1,1,1,8]])
#Comprueba elemento a elemento, el shape tiene que ser igual para poder hacerlo
arr_1 == arr_2

array([[ True,  True,  True, False],
       [ True,  True,  True, False]])

In [74]:
#Tambien esta diferente
arr_1 != arr_2

array([[False, False, False,  True],
       [False, False, False,  True]])

In [75]:
arr_1 <= arr_2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [76]:
arr_1 >= arr_2

array([[ True,  True,  True, False],
       [ True,  True,  True, False]])

In [77]:
#Random function in numpy
np.random.rand(3,4)

array([[0.22174734, 0.56789719, 0.57296903, 0.71993223],
       [0.01047713, 0.87359782, 0.19555131, 0.49265949],
       [0.86803928, 0.28609776, 0.29668533, 0.5178098 ]])

In [78]:
#Esto aun no se que es
np.set_printoptions(precision=3)

In [80]:
#El primer elemento es de 0 hasta donde es el random y el size es como se divide la matriz
np.random.randint(30, size = (4,6))

array([[25,  4, 18,  3, 15, 11],
       [ 8,  9, 17,  8,  5, 27],
       [ 4, 10, 27, 20, 14,  5],
       [ 8, 15, 21, 17, 27, 17]])

In [81]:
np.random.randint(0,30,7)

array([13,  3, 17, 18, 21, 17, 19])

In [82]:
arr_1 = np.arange(100)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [84]:
#mezcla elementos del array
np.random.shuffle(arr_1)
arr_1

array([17, 46, 82, 12, 38, 35, 33, 19, 24, 31, 63, 60, 37, 65, 61, 73, 89,
        0,  7,  9,  3, 81, 84, 59, 41, 97, 69, 55, 15, 75, 52, 30, 20, 91,
       83, 40, 47, 43, 42, 90, 78, 13, 28, 87, 36, 49,  6, 21, 26, 72, 10,
       50, 34, 76, 68, 93, 80, 29, 96, 62, 79, 58, 86,  8, 95, 11, 57, 74,
       45, 48, 16, 67, 23, 99, 70, 51, 39, 44, 92, 22, 64, 54, 14, 88, 56,
       25, 53,  5, 77, 71, 94, 27,  1, 98, 32, 66,  4, 18,  2, 85])

In [90]:
np.random.seed(1) #Valor base para empezar a generar numeros random
np.random.rand(3,3)

array([[4.170e-01, 7.203e-01, 1.144e-04],
       [3.023e-01, 1.468e-01, 9.234e-02],
       [1.863e-01, 3.456e-01, 3.968e-01]])

In [ ]:
#GENERADOR DE SCRIPTS DESDE PYTHON
#Es necesario que no haya comas entre los elementos para crear la matriz

In [6]:
%%writefile np_test1.txt
 
0 1 2 3 4
5 6 7 8 9


Writing np_test1.txt


array([list([]), list([0.0, 1.0, 2.0, 3.0, 4.0]),
       list([5.0, 6.0, 7.0, 8.0, 9.0])], dtype=object)

In [3]:
arr_2 = np.loadtxt("np_test1.txt")
arr_2

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [4]:
%%writefile np_test2.txt

0,1,2,3,4
5,6,7,8,9


Writing np_test2.txt


In [7]:
#Tambien tiene otro parametro llamado skiprows que salta una fila
arr_3 = np.loadtxt("np_test2.txt", delimiter=",")
arr_3

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [8]:
arr_1 = np.array([1,2,3,4,5,6])
arr_1


array([1, 2, 3, 4, 5, 6])

In [9]:
#fmt = "%d" sirve para quitar los decimales ya que siempre los pone, con "%.2f" pone 2 decimales
np.savetxt("np_test3.txt", arr_1,fmt = "%d") 

In [10]:
arr_2 = np.array([1,2,3,4,5,6])
arr_2

array([1, 2, 3, 4, 5, 6])

In [12]:
#Este suele ser el formato preferido y usado por python
np.save("np_test4.npy", arr_2)

In [13]:
#Para abrir y modificar este archivo se hace lo siguiente
arr_3 = np.load("np_test4.npy")
arr_3

array([1, 2, 3, 4, 5, 6])

In [14]:
arr_4 = np.arange(100)
arr_4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
#Este formato sirve para guardar la matriz pero en un formato comprimido
#Guardara en un zip 2 archivos, a.npy que sera la matriz arr_3 y b.npy que sera la matriz arr_4
np.savez("np_test5.npz", a=arr_3, b=arr_4)

In [19]:
#Se abre en memoria como un array
dict_1 = np.load("np_test5.npz")

print(list(dict_1.keys()), dict_1.get("a"), dict_1.get("b"))

['a', 'b'] [1 2 3 4 5 6] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [2]:
#Con el print este sacamos lo que ocupa en memoria el arr_1
import numpy as np
arr_1 = np.zeros((3,3))
print("%d bytes" %(arr_1.size * arr_1.itemsize))

72 bytes


In [4]:
arr_1 = np.ones((4,4))
#Para hacer un marco a una matriz de unos de 4x4, pad_width nos dice el grosor de este maroc
#constant para que sean todos los mismos numeros y constant_values q numero sera
arr_1 = np.pad(arr_1, pad_width=1, mode="constant", constant_values=0)
arr_1

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
#Printear todos los dias de noviembre de 2018
np.arange("2018-11", "2018-12", dtype="datetime64[D]")

array(['2018-11-01', '2018-11-02', '2018-11-03', '2018-11-04',
       '2018-11-05', '2018-11-06', '2018-11-07', '2018-11-08',
       '2018-11-09', '2018-11-10', '2018-11-11', '2018-11-12',
       '2018-11-13', '2018-11-14', '2018-11-15', '2018-11-16',
       '2018-11-17', '2018-11-18', '2018-11-19', '2018-11-20',
       '2018-11-21', '2018-11-22', '2018-11-23', '2018-11-24',
       '2018-11-25', '2018-11-26', '2018-11-27', '2018-11-28',
       '2018-11-29', '2018-11-30'], dtype='datetime64[D]')

In [8]:
#Sacar el entero de un numero con decimales
arr_1 = np.random.rand(5) * 100
np.floor(arr_1) #Tambien vale .round

array([ 9., 59., 20., 93., 84.])

In [4]:
#Crear un array protegido (solo se puede leer)
import numpy as np
arr_1 = np.ones(10)
arr_1.flags.writeable = False
arr_1[0] = 100 #Esta linea dara error

ValueError: assignment destination is read-only